[versions]
minecraft = "26.1.2"
neoForge = "26.1.2.43-beta"
lombok = "9.2.0"
modDevGradle = "2.0.141"
jei = "29.5.0.26"
anvillib = "2.0.0+snapshot.336"

[libraries]
anvillib-network = { group = "dev.anvilcraft.lib", name = "anvillib-network-neoforge-26.1", version.ref = "anvillib" }
jeiApi = { group = "mezz.jei", name = "jei-26.1.2-neoforge-api", version.ref = "jei" }
jei = { group = "mezz.jei", name = "jei-26.1.2-neoforge", version.ref = "jei" }

[bundles]
anvillib = ["anvillib-network"]

[plugins]
modDevGradle = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
